training.set=./dataset/Epinions/train.txt
test.set=./dataset/Epinions/test.txt
model.name=AttentionGNN
model.type=graph
item.ranking=-topN 10,20
embedding.size=64
num.max.epoch=50
batch_size=2048
learnRate=0.001
reg.lambda=0.0001
AttentionGNN=-n_layer 2 -lambda 0.2 -eps 0.1
output.setup=-dir ./results/
